# Generated by Django 4.2.4 on 2023-09-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='imagess')),
                ('status', models.BooleanField(default=False, help_text='0=default,1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=hidden')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('produt_image_1', models.ImageField(upload_to='imagess')),
                ('produt_image_2', models.ImageField(upload_to='imagess')),
                ('produt_image_3', models.ImageField(upload_to='imagess')),
                ('discription', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default,1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
