# Generated by Django 4.2.4 on 2023-09-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousal_img_1', models.ImageField(upload_to='imagess')),
                ('carousal_img_2', models.ImageField(upload_to='imagess')),
                ('carousal_img_3', models.ImageField(upload_to='imagess')),
                ('carousal_img_4', models.ImageField(upload_to='imagess')),
                ('carousal_img_5', models.ImageField(upload_to='imagess')),
            ],
        ),
    ]
