# Generated by Django 4.2.4 on 2023-09-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousal',
            name='carousal_img_4',
        ),
        migrations.RemoveField(
            model_name='carousal',
            name='carousal_img_5',
        ),
    ]
