# Generated by Django 4.2.4 on 2023-09-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='produt_image_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='produt_image_3',
        ),
    ]
