# Generated by Django 4.2.4 on 2023-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_products_produt_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_disc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category_discription',
        ),
    ]
