# Generated by Django 4.2.4 on 2023-09-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='slug',
            new_name='prod_slug',
        ),
    ]
