# Generated by Django 4.2.4 on 2023-09-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_slug_products_prod_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_slug',
            new_name='slug',
        ),
    ]
