# Generated by Django 4.2.4 on 2023-09-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_prod_slug_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cate_slug',
        ),
    ]
