# Generated by Django 4.2.4 on 2023-09-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_slug_category_cate_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate_slug',
            new_name='slug',
        ),
    ]
